version: '2'


services:
  web:
    environment:
      - SECRET=123
    image: exiasr/alpine-yarn-nginx
    ports:
      - "80:3000"
    networks:
      - prodnet
    build:
      context: ../../
      dockerfile: Dockerfile
    links:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - prodnet

networks:
  prodnet:
    driver: bridge
